/**
 * Receipt export. Three formats, no dependency: the image is drawn on a
 * canvas, the PDF is written by hand against one of the base-14 fonts (so
 * nothing has to be embedded), and the CSV is plain text.
 *
 * Everything here runs in the browser — it reads the app's own design tokens
 * off the document so an exported receipt can never drift from the screen.
 */

export type ReceiptRow = { label: string; value: string };

export type Receipt = {
  /** File-name stem and the reference printed on the receipt. */
  reference: string;
  /** Headline outcome, e.g. "Payment Successful". */
  title: string;
  /** The figure, already formatted. */
  amount: string;
  status: string;
  timestamp: string;
  rows: ReceiptRow[];
};

export type ReceiptFormat = "png" | "pdf" | "csv";

const MIME: Record<ReceiptFormat, string> = {
  png: "image/png",
  pdf: "application/pdf",
  csv: "text/csv;charset=utf-8",
};

const BRAND = "Jumpa";
const FOOTER = "Generated by Jumpa. Keep this for your records.";

/** The alpha-trimmed wordmark; the raw logo is mostly padding. */
const LOGO_SRC = "/logo/wordmark/purple.png";
const LOGO_RATIO = 384 / 80;

let logoRequest: Promise<HTMLImageElement> | null = null;

/** Loads the wordmark once. Same-origin, so it never taints a canvas. */
function loadLogo(): Promise<HTMLImageElement> {
  if (!logoRequest) {
    logoRequest = new Promise((resolve, reject) => {
      const image = new Image();
      image.onload = () => resolve(image);
      image.onerror = () => {
        // Clear the cache so a later export can try again.
        logoRequest = null;
        reject(new Error("Could not load the wordmark"));
      };
      image.src = LOGO_SRC;
    });
  }
  return logoRequest;
}

/** Design tokens, read off the document so the file matches the screen. */
function token(name: string, fallback: string): string {
  if (typeof document === "undefined") return fallback;
  const value = getComputedStyle(document.documentElement).getPropertyValue(
    `--color-jumpa-${name}`,
  );
  return value.trim() || fallback;
}

function fontStack(): string {
  if (typeof document === "undefined") return "sans-serif";
  return getComputedStyle(document.body).fontFamily || "sans-serif";
}

export function receiptFilename(
  receipt: Receipt,
  format: ReceiptFormat,
): string {
  const stem = receipt.reference
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
  return `jumpa-receipt-${stem || "transaction"}.${format}`;
}

/* ------------------------------------------------------------------ CSV -- */

/** RFC 4180: quote every field, double any quote inside it. */
function csvCell(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function toCsv(receipt: Receipt): Blob {
  const lines = [
    ["Field", "Value"],
    ["Reference", receipt.reference],
    ["Status", receipt.status],
    ["Amount", receipt.amount],
    ["Date", receipt.timestamp],
    ...receipt.rows.map((row) => [row.label, row.value]),
  ].map((cells) => cells.map(csvCell).join(","));

  // The BOM is what makes Excel read UTF-8 rather than the system code page.
  return new Blob([`﻿${lines.join("\r\n")}\r\n`], { type: MIME.csv });
}

/* ------------------------------------------------------------------ PNG -- */

const PNG_WIDTH = 720; // 360 CSS px at 2x
const PNG_PAD = 48;
const PNG_ROW = 56;
const PNG_LINE = 26;
const PNG_HEAD = 300;
/** Width left for a value once the label column is taken. */
const PNG_VALUE = PNG_WIDTH - PNG_PAD * 2 - 220;
const PNG_LOGO_W = 120;
const PNG_LOGO_H = PNG_LOGO_W / LOGO_RATIO;

/** Draws the receipt and hands back a PNG. Rejects if the canvas is refused. */
async function toPng(receipt: Receipt): Promise<Blob> {
  // The wordmark is decoded before anything is drawn; a receipt that lost its
  // logo halfway through would be worse than one that falls back to the word.
  const logo = await loadLogo().catch(() => null);

  const canvas = document.createElement("canvas");
  canvas.width = PNG_WIDTH;

  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("Canvas is unavailable");

  const family = fontStack();
  const rowFont = `400 19px ${family}`;

  // Measure first: setting the height below resets the context, so the wrap
  // has to be known before the canvas is sized.
  ctx.font = rowFont;
  const wrapped = receipt.rows.map((row) => ({
    label: row.label,
    lines: wrapToWidth(
      row.value,
      PNG_VALUE,
      (text) => ctx.measureText(text).width,
    ),
  }));

  const body = wrapped.reduce(
    (total, row) => total + PNG_ROW + (row.lines.length - 1) * PNG_LINE,
    0,
  );
  const height = PNG_PAD * 2 + PNG_HEAD + body + (body ? 48 : 0);
  canvas.height = height;

  const ink = token("black", "#000000");
  const muted = token("neutral-400", "#818181");
  const brand = token("primary-600", "#8f12ff");
  const surface = token("neutral-50", "#fafafa");
  const hairline = token("neutral-100", "#efefef");

  ctx.fillStyle = token("white", "#ffffff");
  ctx.fillRect(0, 0, PNG_WIDTH, height);

  ctx.fillStyle = brand;
  ctx.fillRect(0, 0, PNG_WIDTH, 8);

  let y = PNG_PAD + 24;

  ctx.textBaseline = "alphabetic";
  if (logo) {
    ctx.drawImage(logo, PNG_PAD, y - PNG_LOGO_H, PNG_LOGO_W, PNG_LOGO_H);
  } else {
    ctx.font = `700 26px ${family}`;
    ctx.fillStyle = brand;
    ctx.fillText(BRAND, PNG_PAD, y);
  }

  ctx.font = `500 20px ${family}`;
  ctx.fillStyle = muted;
  ctx.textAlign = "right";
  ctx.fillText("Transaction receipt", PNG_WIDTH - PNG_PAD, y);
  ctx.textAlign = "left";

  y += 56;
  ctx.fillStyle = surface;
  roundedRect(ctx, PNG_PAD, y, PNG_WIDTH - PNG_PAD * 2, 168, 28);
  ctx.fill();

  const centre = PNG_WIDTH / 2;
  ctx.textAlign = "center";

  ctx.font = `600 44px ${family}`;
  ctx.fillStyle = ink;
  ctx.fillText(receipt.amount, centre, y + 72);

  ctx.font = `500 22px ${family}`;
  ctx.fillText(receipt.title, centre, y + 110);

  ctx.font = `400 18px ${family}`;
  ctx.fillStyle = muted;
  ctx.fillText(receipt.timestamp, centre, y + 142);
  ctx.textAlign = "left";

  y += 168 + 48;

  ctx.font = rowFont;
  for (const row of wrapped) {
    ctx.fillStyle = muted;
    ctx.fillText(row.label, PNG_PAD, y);

    ctx.fillStyle = ink;
    ctx.textAlign = "right";
    row.lines.forEach((line, index) => {
      ctx.fillText(line, PNG_WIDTH - PNG_PAD, y + index * PNG_LINE);
    });
    ctx.textAlign = "left";

    const bottom = y + (row.lines.length - 1) * PNG_LINE + 18;
    ctx.fillStyle = hairline;
    ctx.fillRect(PNG_PAD, bottom, PNG_WIDTH - PNG_PAD * 2, 1);
    y = bottom + PNG_ROW - 18;
  }

  ctx.font = `400 16px ${family}`;
  ctx.fillStyle = muted;
  ctx.fillText(FOOTER, PNG_PAD, height - PNG_PAD + 8);

  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) =>
        blob ? resolve(blob) : reject(new Error("Could not render the image")),
      MIME.png,
    );
  });
}

function roundedRect(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  width: number,
  height: number,
  radius: number,
) {
  ctx.beginPath();
  ctx.moveTo(x + radius, y);
  ctx.arcTo(x + width, y, x + width, y + height, radius);
  ctx.arcTo(x + width, y + height, x, y + height, radius);
  ctx.arcTo(x, y + height, x, y, radius);
  ctx.arcTo(x, y, x + width, y, radius);
  ctx.closePath();
}

/**
 * Breaks a value onto as many lines as it needs. A hash is the proof on a
 * receipt, so it is never cut — a word too long for the line is split.
 */
function wrapToWidth(
  text: string,
  max: number,
  width: (value: string) => number,
): string[] {
  if (width(text) <= max) return [text];

  const lines: string[] = [];
  let line = "";

  for (const word of text.split(" ")) {
    const candidate = line ? `${line} ${word}` : word;
    if (width(candidate) <= max) {
      line = candidate;
      continue;
    }

    if (line) lines.push(line);

    // A single run with no spaces (a hash) is broken character by character.
    line = "";
    for (const char of word) {
      if (width(line + char) > max && line) {
        lines.push(line);
        line = "";
      }
      line += char;
    }
  }

  if (line) lines.push(line);
  return lines;
}

/* ------------------------------------------------------------------ PDF -- */

const PAGE_WIDTH = 595; // A4 at 72dpi
const PAGE_HEIGHT = 842;
const PDF_VALUE_X = 170;
const PDF_LOGO_W = 96;
const PDF_LOGO_H = Math.round((PDF_LOGO_W / LOGO_RATIO) * 100) / 100;

/** Helvetica advances, per point of font size, by character class. The real
 *  metrics are not embedded, and a flat average under-measures an all-caps
 *  address badly enough to run it into the margin. */
const NARROW = /[ijltfrI.,:;'"`|!()[\]{}\-\s]/;
const WIDE = /[A-HJ-Z0-9@#$%&mw]/;

function helveticaWidth(text: string, size: number): number {
  let units = 0;
  for (const char of text) {
    if (NARROW.test(char)) units += 0.3;
    else if (WIDE.test(char)) units += 0.68;
    else units += 0.55;
  }
  return units * size;
}

/** Helvetica is WinAnsi; anything outside it is transliterated or dropped. */
const LATIN1: Record<string, string> = {
  "₦": "NGN ",
  "₵": "GHS ",
  "•": "-",
  "–": "-",
  "—": "-",
  "…": "...",
  "‘": "'",
  "’": "'",
  "“": '"',
  "”": '"',
};

/** Transliterates to the WinAnsi range Helvetica can actually draw. */
function pdfAscii(value: string): string {
  return value
    .replace(/[–—‘’“”•…₦₵]/g, (ch) => LATIN1[ch] ?? "")
    .replace(/[^\x20-\x7e]/g, "");
}

/** Escapes the three characters a PDF string literal reserves. */
function pdfEscape(value: string): string {
  return value.replace(/([\\()])/g, "\\$1");
}

/** `#rrggbb` to the 0–1 triple PDF wants. */
function pdfColour(hex: string): string {
  const value = hex.trim().replace("#", "");
  const full =
    value.length === 3
      ? value
          .split("")
          .map((ch) => ch + ch)
          .join("")
      : value;
  const channel = (at: number) =>
    (Number.parseInt(full.slice(at, at + 2), 16) / 255).toFixed(3);
  return `${channel(0)} ${channel(2)} ${channel(4)}`;
}

/** An image the PDF can carry, with its bytes held as a latin1 string. */
type PdfImage = { data: string; width: number; height: number };

/** Raster width of the embedded wordmark — 3x its printed size, so it stays
 *  crisp when the page is zoomed or printed. */
const PDF_LOGO_RASTER = 288;

/**
 * The wordmark as JPEG. PDF reads JPEG natively through DCTDecode, which is
 * the one image format that needs no compressor of our own.
 */
async function logoJpeg(): Promise<PdfImage | null> {
  const logo = await loadLogo().catch(() => null);
  if (!logo) return null;

  const width = PDF_LOGO_RASTER;
  const height = Math.round(width / LOGO_RATIO);

  const canvas = document.createElement("canvas");
  canvas.width = width;
  canvas.height = height;

  const ctx = canvas.getContext("2d");
  if (!ctx) return null;

  // JPEG carries no alpha, and the page is white — so flatten onto white.
  ctx.fillStyle = "#ffffff";
  ctx.fillRect(0, 0, width, height);
  ctx.drawImage(logo, 0, 0, width, height);

  const url = canvas.toDataURL("image/jpeg", 0.92);
  // atob hands back exactly one character per byte.
  return { data: atob(url.slice(url.indexOf(",") + 1)), width, height };
}

async function toPdf(receipt: Receipt): Promise<Blob> {
  const brand = pdfColour(token("primary-600", "#8f12ff"));
  const ink = pdfColour(token("black", "#000000"));
  const muted = pdfColour(token("neutral-400", "#818181"));
  const surface = pdfColour(token("neutral-50", "#fafafa"));
  const hairline = pdfColour(token("neutral-100", "#efefef"));

  const left = 56;
  const right = PAGE_WIDTH - 56;
  const ops: string[] = [];

  const text = (
    value: string,
    x: number,
    y: number,
    size: number,
    font: "F1" | "F2",
    colour: string,
  ) =>
    ops.push(
      `BT ${colour} rg /${font} ${size} Tf 1 0 0 1 ${x} ${y} Tm (${pdfEscape(pdfAscii(value))}) Tj ET`,
    );

  const rect = (x: number, y: number, w: number, h: number, colour: string) =>
    ops.push(`${colour} rg ${x} ${y} ${w} ${h} re f`);

  rect(0, PAGE_HEIGHT - 8, PAGE_WIDTH, 8, brand);

  let y = PAGE_HEIGHT - 80;

  const logo = await logoJpeg();
  if (logo) {
    // `cm` places the unit image square: width, height, then its bottom-left.
    ops.push(`q ${PDF_LOGO_W} 0 0 ${PDF_LOGO_H} ${left} ${y - 4} cm /Im0 Do Q`);
  } else {
    text(BRAND, left, y, 20, "F2", brand);
  }
  text("Transaction receipt", right - 130, y, 11, "F1", muted);

  y -= 40;
  rect(left, y - 110, right - left, 110, surface);
  text(receipt.amount, left + 24, y - 46, 28, "F2", ink);
  text(receipt.title, left + 24, y - 72, 13, "F1", ink);
  text(receipt.timestamp, left + 24, y - 92, 10, "F1", muted);
  text(receipt.status, right - 90, y - 46, 11, "F2", brand);

  y -= 110 + 48;

  const valueWidth = right - left - PDF_VALUE_X;
  const measure = (value: string) => helveticaWidth(value, 10);

  for (const row of receipt.rows) {
    text(row.label, left, y, 10, "F1", muted);

    const lines = wrapToWidth(pdfAscii(row.value), valueWidth, measure);
    lines.forEach((line, index) => {
      text(line, left + PDF_VALUE_X, y - index * 13, 10, "F2", ink);
    });

    const bottom = y - (lines.length - 1) * 13 - 12;
    rect(left, bottom, right - left, 0.6, hairline);
    y = bottom - 20;
  }

  y -= 12;
  text(`Reference: ${receipt.reference}`, left, y, 9, "F1", muted);
  text(FOOTER, left, 56, 9, "F1", muted);

  return new Blob([assemblePdf(ops.join("\n"), logo)], { type: MIME.pdf });
}

/**
 * Six objects, an xref table and a trailer — the smallest valid PDF, plus a
 * seventh for the wordmark when there is one.
 *
 * The file is built as a latin1 string, one character per byte, so a string
 * offset is the byte offset the xref table has to name even where the JPEG
 * runs outside ASCII.
 */
function assemblePdf(content: string, image: PdfImage | null): ArrayBuffer {
  const resources = image
    ? "/Resources << /Font << /F1 5 0 R /F2 6 0 R >> /XObject << /Im0 7 0 R >> >>"
    : "/Resources << /Font << /F1 5 0 R /F2 6 0 R >> >>";

  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] ` +
      `${resources} /Contents 4 0 R >>`,
    `<< /Length ${content.length} >>\nstream\n${content}\nendstream`,
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>",
  ];

  if (image) {
    objects.push(
      "<< /Type /XObject /Subtype /Image " +
        `/Width ${image.width} /Height ${image.height} ` +
        "/ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode " +
        `/Length ${image.data.length} >>\nstream\n${image.data}\nendstream`,
    );
  }

  let file = "%PDF-1.4\n";
  const offsets: number[] = [];

  objects.forEach((body, index) => {
    offsets.push(file.length);
    file += `${index + 1} 0 obj\n${body}\nendobj\n`;
  });

  const xref = file.length;
  file += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  for (const offset of offsets) {
    file += `${String(offset).padStart(10, "0")} 00000 n \n`;
  }
  file +=
    `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n` +
    `startxref\n${xref}\n%%EOF\n`;

  return latin1(file);
}

/** One byte per character. Handing back the buffer rather than a view keeps
 *  `Blob` happy without a cast. */
function latin1(value: string): ArrayBuffer {
  const buffer = new ArrayBuffer(value.length);
  const bytes = new Uint8Array(buffer);
  for (let index = 0; index < value.length; index += 1) {
    bytes[index] = value.charCodeAt(index) & 0xff;
  }
  return buffer;
}

/* --------------------------------------------------------------- public -- */

export function buildReceipt(
  receipt: Receipt,
  format: ReceiptFormat,
): Promise<Blob> {
  if (format === "csv") return Promise.resolve(toCsv(receipt));
  if (format === "pdf") return toPdf(receipt);
  return toPng(receipt);
}

/** Saves a blob under `filename`, then hands the object URL back. */
export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  // Revoked on the next frame: Safari cancels the save if it goes immediately.
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function canShareFiles(): boolean {
  return (
    typeof navigator !== "undefined" &&
    typeof navigator.canShare === "function" &&
    typeof navigator.share === "function"
  );
}

/** Hands the receipt to the OS share sheet. Returns false if it declined it. */
export async function shareReceipt(
  receipt: Receipt,
  format: ReceiptFormat = "png",
): Promise<boolean> {
  if (!canShareFiles()) return false;

  const blob = await buildReceipt(receipt, format);
  const file = new File([blob], receiptFilename(receipt, format), {
    type: blob.type,
  });
  if (!navigator.canShare({ files: [file] })) return false;

  await navigator.share({ files: [file], title: `${BRAND} receipt` });
  return true;
}

/**
 * A reference for a flow that has no provider id yet. Visibly ours, sortable,
 * and stable once stamped.
 */
export function newReference(prefix: string): string {
  const stamp = new Date().toISOString().replace(/[-:T]/g, "").slice(0, 14);
  return `${prefix}-${stamp}`;
}
