import mongoose, { Schema, model, models } from "mongoose";
import { generateId } from "@/lib/schema-ids";

export interface INgnAccount {
  _id: string;
  userId: string;
  currency: "NGN" | "USD" | string;
  provider: "fossapay" | string;
  status: "pending" | "active" | "failed";

  // Provider-agnostic identifiers
  providerCustomerId?: string | null; // e.g. FossaPay customer UUID
  providerAccountId?: string | null;  // e.g. FossaPay wallet UUID, virtual account ID
  providerReference?: string | null;  // Correlation reference generated by us/wallet id

  //banking details
  bankName?: string | null;
  bankCode?: string | null;
  accountNumber?: string | null;
  accountName?: string | null;

  // Flexible provider metadata (stores vendor-specific raw payloads, tokens, flags)
  providerMetadata?: Record<string, any>;

  // Customer KYC details submitted during creation
  firstName: string;
  middleName?: string | null;
  lastName: string;
  emailAddress: string;
  mobileNumber: string;
  dateOfBirth: string; // YYYY-MM-DD
  address: string;
  city: string;
  country: string; // Full name, e.g. "Nigeria"

  createdAt: Date;
  updatedAt: Date;
}

const NgnAccountSchema = new Schema<INgnAccount>(
  {
    _id: { type: String, default: () => generateId("ngn") },
    userId: { type: String, required: true, index: true },
    currency: { type: String, required: true, default: "NGN" },
    provider: { type: String, required: true, default: "fossapay" },
    status: {
      type: String,
      enum: ["pending", "active", "failed"],
      default: "pending",
    },

    // Provider-agnostic tracking IDs
    providerCustomerId: { type: String, default: null },
    providerAccountId: { type: String, default: null },
    providerReference: { type: String, default: null },

    // Core banking fields
    bankName: { type: String, default: null },
    bankCode: { type: String, default: null },
    accountNumber: { type: String, default: null },
    accountName: { type: String, default: null },

    // Provider-specific metadata dictionary
    providerMetadata: { type: Schema.Types.Mixed, default: {} },

    // KYC details
    firstName: { type: String, required: true },
    middleName: { type: String, default: null },
    lastName: { type: String, required: true },
    emailAddress: { type: String, required: true },
    mobileNumber: { type: String, required: true },
    dateOfBirth: { type: String, required: true },
    address: { type: String, required: true },
    city: { type: String, required: true },
    country: { type: String, required: true },
  },
  { timestamps: true }
);

// One account per currency per provider per user
NgnAccountSchema.index({ userId: 1, currency: 1, provider: 1 }, { unique: true });

// Sparse lookup indexes
NgnAccountSchema.index({ providerCustomerId: 1 }, { sparse: true });
NgnAccountSchema.index({ providerAccountId: 1 }, { sparse: true });
NgnAccountSchema.index({ accountNumber: 1 }, { sparse: true });

export const NgnAccount =
  models.NgnAccount || model<INgnAccount>("NgnAccount", NgnAccountSchema);

// Export alias for future multi-currency / fiat account features
export const FiatAccount = NgnAccount;
export type IFiatAccount = INgnAccount;
